<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vylersant_Facturacion.API</RootNamespace>
    <UserSecretsId>74227b14-953e-4ea5-ae2a-61daeeb42f3d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vylersant-Facturacion.Application\Vylersant-Facturacion.Application.csproj" />
    <ProjectReference Include="..\Vylersant-Facturacion.Contracts\Vylersant-Facturacion.Contracts.csproj" />
    <ProjectReference Include="..\Vylersant-Facturacion.Infrastructure\Vylersant-Facturacion.Infrastructure.csproj" />
  </ItemGroup>

</Project>
